name: HP-ProBookEliteBook

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build HP-ProBookEliteBook
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Manage Version
        run: |
          git fetch --prune --unshallow --tags
          echo "CUR_TAG=$(git tag -l | tail -1)" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Build HP-ProBookEliteBook
        run: |
          chmod +x ./makefile
          
      - name: Prepare Release
        run: |
          make
          (cd "build/" || exit 1)
          releaseItems=(build/Release)
          for releaseItem in "${releaseItems[@]}"; do cp -Rf "${releaseItem}" ./ || exit 1; done

      - name: 'Tar files'
        run: tar -cvf ./build/Release.tar ./build/Release

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: HP-ProBookEliteBook-${{ env.GIT_SHA }}
          path: |
            build/Release.tar
